services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - postgres.env
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

#  ollama:
#    image: ollama/ollama:latest
#    ports:
#      - "11434:11434"
#    volumes:
#      - ./ollama/ollama:/root/.ollama
#      - ./entrypoint.sh:/entrypoint.sh
#    pull_policy: always
#    tty: true
#    restart: always
#    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
#    deploy:
#      resources:
#        limits:
#          cpus: '0.50'
#          memory: 10G
#        reservations:
#          cpus: '0.25'
#          memory: 10G

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
#      - ollama
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tunescout
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=changemeinprod!
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
#      - SPRING_AI_OLLAMA_BASE_URL=http://ollama:11434
      - SPRING_AI_OLLAMA_BASE_URL=http://host.docker.internal:11434
    restart: always
